# Generated by Django 4.2.6 on 2026-02-12 04:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("term", models.CharField(max_length=100)),
                ("class_type", models.CharField(max_length=100)),
                ("course", models.CharField(max_length=100)),
                ("section", models.CharField(max_length=100)),
                ("course_title", models.CharField(max_length=100)),
                ("instructor_first_name", models.CharField(max_length=100)),
                ("instructor_last_name", models.CharField(max_length=100)),
                ("room_name", models.CharField(max_length=100)),
                ("timeslot", models.CharField(max_length=100)),
                ("max_enroll", models.IntegerField()),
                ("room_size", models.IntegerField()),
                ("num_tas", models.IntegerField()),
                (
                    "description",
                    models.CharField(blank=True, max_length=350, null=True),
                ),
                ("status", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("has_discussions", models.BooleanField(default=False)),
                (
                    "current_tas",
                    models.ManyToManyField(
                        blank=True,
                        related_name="course_working_for",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "professor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
