# Generated by Django 4.2.6 on 2026-02-12 05:10

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_studentprofile_pastcourse"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="cv",
            field=models.FileField(
                blank=True, null=True, upload_to=users.models.cv_upload_path
            ),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="profile_photo",
            field=models.FileField(
                blank=True, null=True, upload_to=users.models.profile_photo_upload_path
            ),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="resume",
            field=models.FileField(
                blank=True, null=True, upload_to=users.models.resume_upload_path
            ),
        ),
    ]
