# Generated by Django 4.2.6 on 2026-02-12 05:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_add_cv_and_profile_photo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="skills",
            field=models.ManyToManyField(
                blank=True, related_name="profiles", to="users.skill"
            ),
        ),
    ]
