# Generated by Django 4.2.6 on 2026-02-12

from django.db import migrations


PREDEFINED_SKILLS = [
    'Python', 'Java', 'C', 'C++', 'JavaScript', 'MATLAB', 'R',
    'LaTeX', 'Git', 'Debugging', 'SQL', 'HTML/CSS', 'Linux/Unix',
    'Data Structures', 'Algorithms', 'Object-Oriented Programming',
    'Tutoring', 'Office Hours', 'Grading', 'Technical Writing',
]


def add_skills(apps, schema_editor):
    Skill = apps.get_model('users', 'Skill')
    for name in PREDEFINED_SKILLS:
        Skill.objects.get_or_create(name=name)


def remove_skills(apps, schema_editor):
    Skill = apps.get_model('users', 'Skill')
    Skill.objects.filter(name__in=PREDEFINED_SKILLS).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_add_skills"),
    ]

    operations = [
        migrations.RunPython(add_skills, remove_skills),
    ]
