# Generated by Django 4.2.6 on 2026-04-09 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_populate_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='graduation_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
