# Generated by Django 4.2.6 on 2026-04-10 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_student_employment_onboarding_checklist"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pastcourse",
            name="grade",
        ),
        migrations.AddField(
            model_name="customuser",
            name="profile_welcome_acknowledged",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="skills_additional",
            field=models.CharField(
                blank=True,
                help_text="Skills not listed in the picker (comma-separated or short phrases).",
                max_length=500,
            ),
        ),
    ]
