from django.urls import path, include
from . import views
from users.views import StudentProfileView
from .help_views import help_home, help_print, help_students_print, help_students_search, help_student_topic

urlpatterns = [
    path("", views.home, name="home"),
    path("contributors/", views.contributors, name="contributors"),
    path("welcome/", views.profile_welcome, name="profile_welcome"),
    path("help/", help_home, name="help_home"),
    path("help/print/", help_print, name="help_print"),
    path("help/students/print/", help_students_print, name="help_students_print"),
    path("help/students/search/", help_students_search, name="help_students_search"),
    path("help/students/<str:topic_id>/", help_student_topic, name="help_student_topic"),
    path("dashboard/", views.admin_dashboard_v2, name="dashboard"),
    path("notifications/", views.notifications_page, name="notifications"),
    path("notifications/<uuid:notification_id>/open/", views.open_notification, name="open_notification"),
    path("notifications/<uuid:notification_id>/dismiss/", views.dismiss_notification, name="dismiss_notification"),
    path("notifications/clear/", views.clear_notifications, name="clear_notifications"),
    path("profile/", StudentProfileView.as_view(), name="student_profile"),
    path(
        "employment-onboarding/",
        views.employment_onboarding_checklist,
        name="employment_onboarding",
    ),
    path("applications/", views.applications_list_v2, name="applications"),
    path("offers/", views.offers_list_v2, name="offers"),
    path("courses/", views.courses_list_v2, name="courses"),
    path("courses/create/", views.create_course_v2, name="create_course"),
    path("courses/<uuid:course_id>/", views.course_overview_v2, name="course_overview"),
    path("courses/<uuid:course_id>/edit/", views.edit_course_v2, name="edit_course"),
    path("courses/<uuid:course_id>/remove-ta/<uuid:user_id>/", views.remove_ta_v2, name="remove_ta"),
    path("courses/<uuid:course_id>/questions/add/", views.add_course_question_v2, name="add_course_question"),
    path("courses/<uuid:course_id>/questions/<uuid:question_id>/delete/", views.delete_course_question_v2, name="delete_course_question"),
    path("courses/<uuid:course_id>/delete/", views.delete_course_v2, name="delete_course"),
    path("courses/upload/", views.upload_courses_v2, name="upload_courses"),
    path("courses/export/", views.export_schedule, name="export_schedule"),
    path("courses/close/", views.close_semester_v2, name="close_semester"),
    path("apply/<uuid:course_id>/", views.apply_to_course_v2, name="apply_to_course"),
    path("make-offer/<uuid:application_id>/", views.make_offer_v2, name="make_offer"),
    path("reject-application/<uuid:application_id>/", views.reject_application_v2, name="reject_application"),
    path("application/<uuid:application_id>/withdraw/", views.withdraw_application_v2, name="withdraw_application"),
    path("application/<uuid:application_id>/edit/", views.edit_application_v2, name="edit_application"),
    path("accept-offer/<uuid:offer_id>/", views.accept_offer_v2, name="accept_offer"),
    path("decline-offer/<uuid:offer_id>/", views.decline_offer_v2, name="decline_offer"),
    path("application/<uuid:application_id>/", views.application_detail_v2, name="application_detail"),
    path("application/<uuid:application_id>/resume/", views.serve_application_resume, name="serve_application_resume"),
    path(
        "application/<uuid:application_id>/photo/",
        views.serve_application_applicant_photo,
        name="serve_application_applicant_photo",
    ),
    path("onboarding-status/", views.onboarding_status_v2, name="onboarding_status"),
    path("onboarding-status/export/", views.export_onboarding_status, name="export_onboarding_status"),
    path("onboarding-status/remind/", views.send_onboarding_reminders, name="send_onboarding_reminders"),
    path("evaluations/", include("evaluations.urls")),
]
