# Generated by Django 4.2.6 on 2026-02-17 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='withdrawal_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.IntegerField(choices=[(1, 'PENDING'), (2, 'ACCEPTED'), (3, 'REJECTED'), (4, 'CONFIRMED'), (5, 'WITHDRAWN')], default=1),
        ),
    ]
