# Generated by Django 4.2.6 on 2026-03-27 01:24

import applications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0002_add_withdrawn_status_and_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="courses_snapshot",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="application",
            name="other_notes",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="application",
            name="relevant_experience",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="application",
            name="resume",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=applications.models.application_resume_upload_path,
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="skills_snapshot",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="application",
            name="why_this_course",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
