# Generated by Django 4.2.6 on 2026-04-10 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_application_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='skills_additional_snapshot',
            field=models.CharField(blank=True, help_text='Free-text skills from profile at time of application.', max_length=500),
        ),
    ]
