# Generated by Django 4.2.6 on 2026-04-10 16:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_coursequestion"),
        ("applications", "0005_skills_additional_and_prune"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicationAnswer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("answer_text", models.CharField(blank=True, max_length=500)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_answers",
                        to="applications.application",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="answers",
                        to="courses.coursequestion",
                    ),
                ),
            ],
            options={
                "unique_together": {("application", "question")},
            },
        ),
    ]
